name: reviewdog
on: [push, pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          stylelint_input: '**/*.less'
          stylelint_config: '.stylelintrc.json'
          packages: 'stylelint-config-prettier stylelint-config-standard'
