on:
  push:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn # OR: yarn

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v14
        with:
          config_path: '.eslintrc.json'
          # ignore_path: '/path/to/.eslintignore'
          extra_args: '--max-warnings=0'
