name: Test
on: [push]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master
        with:
          node-version: 16
        env:
          PATTERN: '*.less'
