name: reviewdog
on: [pull_request, push]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          level: error
          reporter: github-pr-check
          eslint_flags: '--quiet --cache --ext .js,.jsx,.ts,.tsx .'
          filter_mode: diff_context
          fail_on_error: true
