name: Create Release
on: [push, pull_request]

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using stylelint
        uses: moneyforward/stylelint-action@v0
        with:
          options: '["-s", "less"]'
