name: Create Release
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [16]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.2.0

      - name: Install Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}

      - run: yarn ci
