name: reviewdog
on:
  push:
    branches-ignore: [master, main]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          level: error
          reporter: github-check
          eslint_flags: '--quiet --cache --ext .js,.jsx,.ts,.tsx .'
          fail_on_error: true
